<?php
/**
 * @file
 * The functions for the Custom CuritibaCultura module.
 */

/**
 * Implements hook_block_info().
 */
function custom_ctbacult_block_info() {
  $blocks = array();
  $blocks['where_to_go'] = array(
    'info' => t('You do not know where to go today?'),
  );
  return $blocks;
}
/**
 * Implements hook_block_view().
 */
function custom_ctbacult_block_view($delta='') {
  $block = array();
  switch ($delta) {
    case 'where_to_go':
      $block['subject'] = t('You do not know where to go today?');
      $block['content'] = views_embed_view('estabelecimentos','block_1');
    break;
  }
  return $block;
}

/**
 * Implements hook_token_info().
 */
function custom_ctbacult_token_info() {
  $info = array();
  $info['types']['ctbacult'] = array(
    'name' => t('CuritibaCultura'),
    'description' => t('A token type for CuritibaCultura tokens.'),
  );
  $info['tokens']['ctbacult']['video_image'] = array(
    'name' => t('Video image'),
    'description' => t('Video image'),
  );
  $info['tokens']['ctbacult']['video_url'] = array(
    'name' => t('Video url'),
    'description' => t('Video url'),
  );
  $info['tokens']['ctbacult']['images'] = array(
    'name' => t('Images: 0'),
    'description' => t('Image position 0'),
  );
  $info['tokens']['ctbacult']['images_1'] = array(
    'name' => t('Images: 1'),
    'description' => t('Image position 1'),
  );
  $info['tokens']['ctbacult']['images_2'] = array(
    'name' => t('Images: 2'),
    'description' => t('Image position 2'),
  );
  $info['tokens']['ctbacult']['images_3'] = array(
    'name' => t('Images: 3'),
    'description' => t('Image position 3'),
  );
  $info['tokens']['ctbacult']['images_4'] = array(
    'name' => t('Images: 4'),
    'description' => t('Image position 4'),
  );
  return $info;
}

function custom_ctbacult_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();

  if ($type == 'ctbacult') {
    foreach ($tokens as $name => $original) {

      switch ($name) {
        case 'video_image':
          if ($data['node']->field_video == true) {
            $file_id = strip_tags($data['node']->field_video['und'][0]['fid']);
            $file_path = file_load($file_id)->uri;
            $string = file_create_url($file_path);
            if (strstr($string, "youtube")) {
              $image_video = str_replace("http://www.youtube.com/watch?v=", "", $string);
              $value = 'http://www.curitibacultura.com.br/sites/default/files/media-youtube/'. $image_video .'.jpg';
            } elseif (strstr($string, "vimeo")) {
              $image_video = str_replace("http://vimeo.com/", "", $string);
              $value = 'http://www.curitibacultura.com.br/sites/default/files/media-vimeo/'. $image_video .'.jpg';
            }
          }
        $replacements[$original] = $value;
        break;

        case 'video_url':
          if ($data['node']->field_video == true) {
            $file_id = strip_tags($data['node']->field_video['und'][0]['fid']);
            $file_path = file_load($file_id)->uri;
            // print file_create_url($file_path);
            $string = file_create_url($file_path);

            if (strstr($string, "youtube")) {
              $youtube = str_replace("http", "https", $string);
              $value = str_replace("watch?v=", "embed/", $youtube);
            } elseif (strstr($string, "vimeo")) {
              $value = str_replace("http://vimeo.com/", "https://player.vimeo.com/video/", $string);
            }
          }
        $replacements[$original] = $value;
        break;

        case 'images':
          if ($data['node']->field_images == true) {
            $value = image_style_url('facebook_600x316', $data['node']->field_images['und'][0]['uri']);
          }
        $replacements[$original] = $value;
        break;

        case 'images_1':
          if ($data['node']->field_images == true) {
            $value = image_style_url('facebook_600x316', $data['node']->field_images['und'][1]['uri']);
          }
        $replacements[$original] = $value;
        break;

        case 'images_2':
          if ($data['node']->field_images == true) {
            $value = image_style_url('facebook_600x316', $data['node']->field_images['und'][2]['uri']);
          }
        $replacements[$original] = $value;
        break;

        case 'images_3':
          if ($data['node']->field_images == true) {
            $value = image_style_url('facebook_600x316', $data['node']->field_images['und'][3]['uri']);
          }
        $replacements[$original] = $value;
        break;

        case 'images_4':
          if ($data['node']->field_images == true) {
            $value = image_style_url('facebook_600x316', $data['node']->field_images['und'][4]['uri']);
          }
        $replacements[$original] = $value;
        break;

      }
    }
  }

  return $replacements;
}

/*
 * Implements custom view mode hook_entity_info_alter().
 */

function custom_ctbacult_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes']['thumb_video'] = array(
    'label' => t('Thumbnail video'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['player_video'] = array(
    'label' => t('Player video node'),
    'custom settings' => TRUE,
  );
  $entity_info['file']['view modes']['player_video_block'] = array(
    'label' => t('Player video block'),
    'custom settings' => TRUE,
  );
}

function custom_ctbacult_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_login_block' || $form_id == 'user_login') {
    honeypot_add_form_protection($form, $form_state, array('honeypot', 'time_restriction'));
  }
}
